name: Pull Request CI

on: [pull_request, push]

jobs:
  testE2E:
    name: E2E Tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      COMPOSE_PROJECT_NAME: issue-repro

    steps:
      - uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: https://github.com/docker/buildx.git#master

      # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: false # Do not push, only build and cache
          load: true # Enable accessing output from other steps
          tags: builder:latest
          target: builder
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            CI=true

      - name: E2E Tests
        run: docker run --net="issue-repro_default" builder:latest /bin/sh -c 'yarn test:e2e:ci;'

        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
